// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SebastianLargo_Examen1P.Data;

#nullable disable

namespace SebastianLargo_Examen1P.Migrations
{
    [DbContext(typeof(SebastianLargo_Examen1PContext))]
    [Migration("20240424154852_CreacionTabla")]
    partial class CreacionTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SebastianLargo_Examen1P.Models.SL_modelo1", b =>
                {
                    b.Property<int>("SLPerfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLPerfilID"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SLCaracter")
                        .HasColumnType("bit");

                    b.Property<int>("SLDecimal")
                        .HasColumnType("int");

                    b.Property<string>("SLNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLPerfilID");

                    b.ToTable("SL_modelo1");
                });
#pragma warning restore 612, 618
        }
    }
}
